#!/bin/bash

# Pressing CTRL-C will stop the whole execution of the script
trap ctrl_c INT; 
function ctrl_c() { exit 5; }

# variables

CMD_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}" )" && pwd)
CMD_NAME=$(basename "${BASH_SOURCE[0]}")
TRAIN_FILE=""
WEIGHTED=false
VISIBLE_VARIABLE_TYPE="Bernoulli"
INFO=false
TRAIN_OPTIONS=()

function print_usage() {
    echo -en "USAGE: ${CMD_NAME} [-w] [-V] [-i] [-h] [training options]\n"
    echo -en "\n"
    echo -en "Optional arguments:\n
    -w, --weighted\t\tOption for weighted training.
    -V, --vis-vars <name>\tVisible variables type. Implemented are \"Bernoulli\" and \"Potts\".
    -i, --info\t\t\tShows the possible options for training the specified model.
    -h, --help\t\t\tPrint this help message.
    --[option] <value>\t\tTraining options for the selected model.\n\n"
}

while [ -n "${1}" ]; do
    case ${1} in
        -w|--weighted)
            WEIGHTED=true
            ;;
        -V|--vis-vars)
            shift
            VISIBLE_VARIABLE_TYPE=${1}
            ;;
        -h|--help) 
            print_usage
            exit 0
            ;;
        -i|--info)
            INFO=true
            ;;
        *)
            TRAIN_OPTIONS+=( $1 )
            shift
            continue
            ;;
        --)
            shift
            break
            ;;
    esac
    shift
done

if $WEIGHTED
then
    TRAIN_FILE="${CMD_DIR}/src/train/train${VISIBLE_VARIABLE_TYPE}BernoulliWeightedRBM.py"
else
    TRAIN_FILE="${CMD_DIR}/src/train/train${VISIBLE_VARIABLE_TYPE}BernoulliRBM.py"
fi

export HOME_PATH=$CMD_DIR
if $INFO
then
    python3 "${TRAIN_FILE}" --help
else
    python3 "${TRAIN_FILE}" ${TRAIN_OPTIONS[@]}
fi